#!/bin/bash

set -eux

# If CI env var is "yes" move my CI config into place
if [ "${ci}" == "yes" ]; then
	mv /ci/pxls.conf /pxls.conf
fi


# If config is mounted to /pxls.conf, move it to workdir
if [[ -f /pxls.conf ]]; then
	echo "Custom Pxls Config File Detected, Using that"
	cp /pxls.conf ./pxls.conf
else
	echo "No pxls.conf detected, aborting"
	exit 1
fi
