---
version: '3.2'
services:
  pxls:
    image: m08y/docker-pxls.space 
    ports:
      - "80:4567/tcp"
    environment:
      dbhost: pxls-postgres
      dbuser: pxls
      dbpass: pxls
      dbname: pxls
      authuseip: "true"
  pxls-postgres:    
    image: postgres
    environment:
      POSTGRES_USER: pxls
      POSTGRES_PASSWORD: pxls
      POSTGRES_DATABASE: pxls
