---
version: '3.2'
services:
  pxls:
    image: m08y/docker-pxls.space 
    ports:
      - "80:4567/tcp"
    environment:
      dbhost: pxls-mysql
      dbuser: pxls
      dbpass: YOU MUST SET THIS YOURSELF 
      dbname: pxls
      useip: "true"
  pxls-mysql:    
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: pxls
      MYSQL_PASSWORD: YOU MUST SET THIS YOURSELF
      MYSQL_DATABASE: pxls
