#!/bin/bash

set -eux

# Testing, avoid all permission issues
chmod 775 /Pxls -R

cd /Pxls && echo "cd Successful"

cp /config ./pxls.conf

sed 's/@dbhost@/"$dbhost"/g'
sed 's/@dbport@/"$dbport"/g'
sed 's/@dbuser@/"$dbuser"/g'
sed 's/@dbpass@/"$dbpass"/g'
sed 's/@dbname@/"$dbname"/g'


java -jar ./target/pxls-1.0-SNAPSHOT.jar
