#!/bin/bash

set -eux

# Testing, avoid all permission issues
chmod 775 /Pxls -R

cd /Pxls && echo "cd Successful"

cp /pxls.conf ./pxls.conf

#sed -i "s/@dbhost@/"$dbhost"/g" ./pxls.conf
#sed -i "s/@dbport@/"$dbport"/g" ./pxls.conf
#sed -i "s/@dbuser@/"$dbuser"/g" ./pxls.conf
#sed -i "s/@dbpass@/"$dbpass"/g" ./pxls.conf
#sed -i "s/@dbname@/"$dbname"/g" ./pxls.conf

sed -i "s|@dbhost@|$dbhost|g" ./pxls.conf
sed -i "s|@dbport@|$dbport|g" ./pxls.conf
sed -i "s|@dbuser@|$dbuser|g" ./pxls.conf
sed -i "s|@dbpass@|${dbpass}|g" ./pxls.conf
sed -i "s|@dbname@|$dbname|g" ./pxls.conf
sed -i "s|@apaddress@|$ipaddress|g" ./pxls.conf

cat ./pxls.conf

java -jar ./target/pxls-1.0-SNAPSHOT.jar
